// <auto-generated />
using Favourites.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Favourites.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240126075018_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Favourites.Domain.Entities.Favourite.FavouritesDetails", b =>
                {
                    b.Property<int>("FavouritesDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FavouritesDetailsId"));

                    b.Property<int>("FavouritesHeaderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("FavouritesDetailsId");

                    b.HasIndex("FavouritesHeaderId");

                    b.ToTable("FavouritesDetails");
                });

            modelBuilder.Entity("Favourites.Domain.Entities.Favourite.FavouritesHeader", b =>
                {
                    b.Property<int>("FavouritesHeaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FavouritesHeaderId"));

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("FavouritesHeaderId");

                    b.ToTable("FavouritesHeaders");
                });

            modelBuilder.Entity("Favourites.Domain.Entities.Favourite.FavouritesDetails", b =>
                {
                    b.HasOne("Favourites.Domain.Entities.Favourite.FavouritesHeader", "FavouritesHeader")
                        .WithMany()
                        .HasForeignKey("FavouritesHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FavouritesHeader");
                });
#pragma warning restore 612, 618
        }
    }
}
