//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coupon.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Coupon.Application.Resources.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите хотя бы один купон для удаления.
        /// </summary>
        internal static string ChooseOneOrMoreCoupons {
            get {
                return ResourceManager.GetString("ChooseOneOrMoreCoupons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такой купон уже существует.
        /// </summary>
        internal static string CouponAlreadyExists {
            get {
                return ResourceManager.GetString("CouponAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код купона не валидный.
        /// </summary>
        internal static string CouponCodeNotValid {
            get {
                return ResourceManager.GetString("CouponCodeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Купон не может быть создан.
        /// </summary>
        internal static string CouponNotCreated {
            get {
                return ResourceManager.GetString("CouponNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Купон не может быть удален.
        /// </summary>
        internal static string CouponNotDeleted {
            get {
                return ResourceManager.GetString("CouponNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такого купона не существует.
        /// </summary>
        internal static string CouponNotDeletedCatch {
            get {
                return ResourceManager.GetString("CouponNotDeletedCatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таких купонов не существует.
        /// </summary>
        internal static string CouponNotDeletedListCatch {
            get {
                return ResourceManager.GetString("CouponNotDeletedListCatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Купон не найден.
        /// </summary>
        internal static string CouponNotFound {
            get {
                return ResourceManager.GetString("CouponNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Купон не может быть обновлен.
        /// </summary>
        internal static string CouponNotUpdated {
            get {
                return ResourceManager.GetString("CouponNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такого купона не существует.
        /// </summary>
        internal static string CouponNotUpdatedNull {
            get {
                return ResourceManager.GetString("CouponNotUpdatedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Купоны не найдены.
        /// </summary>
        internal static string CouponsNotFound {
            get {
                return ResourceManager.GetString("CouponsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма скидки купона не может превышать стоимость продукта.
        /// </summary>
        internal static string DiscountAmountNotValid {
            get {
                return ResourceManager.GetString("DiscountAmountNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внутренняя проблема сервера.
        /// </summary>
        internal static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма для применения купона не валидна.
        /// </summary>
        internal static string MinAmountNotValid {
            get {
                return ResourceManager.GetString("MinAmountNotValid", resourceCulture);
            }
        }
    }
}
