//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Identity.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SuccessMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SuccessMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Identity.Application.Resources.SuccessMessage", typeof(SuccessMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы успешно вошли в аккаунт.
        /// </summary>
        internal static string SuccessfullyLogin {
            get {
                return ResourceManager.GetString("SuccessfullyLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы успешно зарегистрировались.
        /// </summary>
        internal static string SuccessfullyRegister {
            get {
                return ResourceManager.GetString("SuccessfullyRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Токены всех пользователей успешно удалены.
        /// </summary>
        internal static string TokensSuccessfullyDeleted {
            get {
                return ResourceManager.GetString("TokensSuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Токен пользователя успешно удален.
        /// </summary>
        internal static string TokenSuccessfullyDeleted {
            get {
                return ResourceManager.GetString("TokenSuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Токены успешно обновлены.
        /// </summary>
        internal static string TokensUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("TokensUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль пользователя успешно обновлен.
        /// </summary>
        internal static string UserProfileSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("UserProfileSuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи успешно удалены.
        /// </summary>
        internal static string UsersSuccessfullyDeleted {
            get {
                return ResourceManager.GetString("UsersSuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи успешно получены.
        /// </summary>
        internal static string UsersSuccessfullyGeted {
            get {
                return ResourceManager.GetString("UsersSuccessfullyGeted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь успешно создан.
        /// </summary>
        internal static string UserSuccessfullyCreated {
            get {
                return ResourceManager.GetString("UserSuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь успешно удален.
        /// </summary>
        internal static string UserSuccessfullyDeleted {
            get {
                return ResourceManager.GetString("UserSuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полььзователь успешно получен.
        /// </summary>
        internal static string UserSuccessfullyGot {
            get {
                return ResourceManager.GetString("UserSuccessfullyGot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь успешно обновлен.
        /// </summary>
        internal static string UserSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("UserSuccessfullyUpdated", resourceCulture);
            }
        }
    }
}
