//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coupon.Application.Resources.Features.Coupons.Handlers.Commands {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessage_ru_RU1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage_ru_RU1() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Coupon.Application.Resources.Features.Coupons.Handlers.Commands.ErrorMessage.ru-R" +
                            "U1", typeof(ErrorMessage_ru_RU1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Такой купон уже существует.
        /// </summary>
        public static string CouponAlreadyExists {
            get {
                return ResourceManager.GetString("CouponAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код купона не валидный.
        /// </summary>
        public static string CouponCodeNotValid {
            get {
                return ResourceManager.GetString("CouponCodeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Купон не может быть создан.
        /// </summary>
        public static string CouponNotCreated {
            get {
                return ResourceManager.GetString("CouponNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Купон не может быть удален.
        /// </summary>
        public static string CouponNotDeleted {
            get {
                return ResourceManager.GetString("CouponNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Такого купона не существует.
        /// </summary>
        public static string CouponNotDeletedCatch {
            get {
                return ResourceManager.GetString("CouponNotDeletedCatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Таких купонов не существует.
        /// </summary>
        public static string CouponNotDeletedListCatch {
            get {
                return ResourceManager.GetString("CouponNotDeletedListCatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Купон не найден.
        /// </summary>
        public static string CouponNotFound {
            get {
                return ResourceManager.GetString("CouponNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Купон не может быть обновлен.
        /// </summary>
        public static string CouponNotUpdated {
            get {
                return ResourceManager.GetString("CouponNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Такого купона не существует.
        /// </summary>
        public static string CouponNotUpdatedNull {
            get {
                return ResourceManager.GetString("CouponNotUpdatedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Купоны не найдены.
        /// </summary>
        public static string CouponsNotFound {
            get {
                return ResourceManager.GetString("CouponsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сумма скидки купона не может превышать стоимость продукта.
        /// </summary>
        public static string DiscountAmountNotValid {
            get {
                return ResourceManager.GetString("DiscountAmountNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внутренняя проблема сервера.
        /// </summary>
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сумма для применения купона не валидна.
        /// </summary>
        public static string MinAmountNotValid {
            get {
                return ResourceManager.GetString("MinAmountNotValid", resourceCulture);
            }
        }
    }
}
